### ISSUE TITLE
feathers-action

### ISSUE THREAD

**Issue by pietgeursen** [dogstack/dogstack-example#9]

**Comment by ahdinosaur** [comment]
question is whether it's worth pushing `feathers-action@v2`, written to heavily use `tcomb`, over the edge, OR start over. so far working with the code there has been good, but i can tell there's extra complexity due to tcombing all the things, when maybe we might eventually go with a different schema / validation systems like plain old JSON schema.

**Comment by ahdinosaur** [comment]
done with #16
